In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

df = pd.read_excel("ENERGY EFFICIENCY & WASTE.xlsx")
df.head()

,Timestamp,MachineID,Plant,Temperature,Vibration,Pressure,EnergyConsumption,ProductionUnits,DefectCount,MaintenanceFlag
0,2025-01-01 00:00:00,140,Plant_C,73.585558,2.266289,20.785937,289.823429,128,2,0
1,2025-01-01 01:00:00,115,Plant_A,76.981562,3.326905,31.464005,181.688138,160,2,0
2,2025-01-01 02:00:00,145,Plant_C,68.554217,5.285392,30.768659,257.077101,79,3,0
3,2025-01-01 03:00:00,108,Plant_C,92.756558,6.289777,33.924396,217.046652,146,5,1
4,2025-01-01 04:00:00,122,Plant_C,76.174981,7.844886,25.129085,251.312522,142,4,0

In [ ]:
df.columns

Index(['Timestamp', 'MachineID', 'Plant', 'Temperature', 'Vibration',
       'Pressure', 'EnergyConsumption', 'ProductionUnits', 'DefectCount',
       'MaintenanceFlag'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Timestamp          20000 non-null  datetime64[ns]
 1   MachineID          20000 non-null  int64
 2   Plant              20000 non-null  object
 3   Temperature        20000 non-null  float64
 4   Vibration          20000 non-null  float64
 5   Pressure           20000 non-null  float64
 6   EnergyConsumption  20000 non-null  float64
 7   ProductionUnits    20000 non-null  int64
 8   DefectCount        20000 non-null  int64
 9   MaintenanceFlag    20000 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(4), object(1)
memory usage: 1.5+ MB

In [ ]:
df.isnull().sum()

Timestamp            0
MachineID            0
Plant                0
Temperature          0
Vibration            0
Pressure             0
EnergyConsumption    0
ProductionUnits      0
DefectCount          0
MaintenanceFlag      0
dtype: int64

In [ ]:
import pandas as pd

In [ ]:
df = pd.get_dummies(df, columns=['MachineID', 'Plant'], drop_first=True)
df.head()

,Timestamp,Temperature,Vibration,Pressure,EnergyConsumption,ProductionUnits,DefectCount,MaintenanceFlag,MachineID_101,MachineID_102,...,MachineID_142,MachineID_143,MachineID_144,MachineID_145,MachineID_146,MachineID_147,MachineID_148,MachineID_149,Plant_Plant_B,Plant_Plant_C
0,2025-01-01 00:00:00,73.585558,2.266289,20.785937,289.823429,128,2,0,False,False,...,False,False,False,False,False,False,False,False,False,True
1,2025-01-01 01:00:00,76.981562,3.326905,31.464005,181.688138,160,2,0,False,False,...,False,False,False,False,False,False,False,False,False,False
2,2025-01-01 02:00:00,68.554217,5.285392,30.768659,257.077101,79,3,0,False,False,...,False,False,False,True,False,False,False,False,False,True
3,2025-01-01 03:00:00,92.756558,6.289777,33.924396,217.046652,146,5,1,False,False,...,False,False,False,False,False,False,False,False,False,True
4,2025-01-01 04:00:00,76.174981,7.844886,25.129085,251.312522,142,4,0,False,False,...,False,False,False,False,False,False,False,False,False,True

In [ ]:
df = df.drop('Timestamp', axis=1)

In [ ]:
X = df.drop("EnergyConsumption", axis=1)
y = df["EnergyConsumption"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [ ]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor()
rf.fit(X_train, y_train)

RandomForestRegressor()

In [ ]:
from sklearn.metrics import mean_squared_error
import numpy as np

# Linear Regression
y_pred_lr = lr.predict(X_test)
rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))

# Random Forest
y_pred_rf = rf.predict(X_test)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))

print("Linear RMSE:", rmse_lr)
print("Random Forest RMSE:", rmse_rf)

Linear RMSE: 39.84259253273305
Random Forest RMSE: 40.52805250858825

In [ ]:
df['EnergyPerUnit'] = df['EnergyConsumption'] / df['ProductionUnits']
df.head()

,Temperature,Vibration,Pressure,EnergyConsumption,ProductionUnits,DefectCount,MaintenanceFlag,MachineID_101,MachineID_102,MachineID_103,...,MachineID_143,MachineID_144,MachineID_145,MachineID_146,MachineID_147,MachineID_148,MachineID_149,Plant_Plant_B,Plant_Plant_C,EnergyPerUnit
0,73.585558,2.266289,20.785937,289.823429,128,2,0,False,False,False,...,False,False,False,False,False,False,False,False,True,2.264246
1,76.981562,3.326905,31.464005,181.688138,160,2,0,False,False,False,...,False,False,False,False,False,False,False,False,False,1.135551
2,68.554217,5.285392,30.768659,257.077101,79,3,0,False,False,False,...,False,False,True,False,False,False,False,False,True,3.254141
3,92.756558,6.289777,33.924396,217.046652,146,5,1,False,False,False,...,False,False,False,False,False,False,False,False,True,1.486621
4,76.174981,7.844886,25.129085,251.312522,142,4,0,False,False,False,...,False,False,False,False,False,False,False,False,True,1.769806

In [ ]:
df['EnergyPerUnit'].describe()

count    20000.000000
mean         2.317370
std          1.048599
min          0.593320
25%          1.526715
50%          2.004940
75%          2.864298
max          6.730998
Name: EnergyPerUnit, dtype: float64

In [ ]:
from scipy.stats import zscore

df['Z_score'] = zscore(df['EnergyPerUnit'])

anomalies_z = df[df['Z_score'].abs() > 3]

anomalies_z.head()

,Temperature,Vibration,Pressure,EnergyConsumption,ProductionUnits,DefectCount,MaintenanceFlag,MachineID_101,MachineID_102,MachineID_103,...,MachineID_144,MachineID_145,MachineID_146,MachineID_147,MachineID_148,MachineID_149,Plant_Plant_B,Plant_Plant_C,EnergyPerUnit,Z_score
94,66.484017,2.748175,29.355462,329.311263,51,0,0,False,False,False,...,False,False,False,False,False,False,False,False,6.457084,3.947951
129,70.730706,4.775016,27.632971,282.909700,50,1,0,False,False,False,...,False,False,False,False,False,False,False,False,5.658194,3.186068
218,83.795979,4.945003,23.094503,334.514577,50,3,0,False,False,False,...,False,False,False,False,False,False,False,True,6.690292,4.170356
226,87.495133,3.270893,40.024504,327.327941,55,3,0,False,False,False,...,False,False,False,False,False,False,True,False,5.951417,3.465708
679,75.051752,5.343318,17.549094,320.538072,53,2,0,False,False,False,...,False,False,False,False,False,False,False,True,6.047888,3.557710

In [ ]:
from sklearn.ensemble import IsolationForest

iso = IsolationForest(contamination=0.05, random_state=42)

df['anomaly'] = iso.fit_predict(df[['EnergyPerUnit']])

anomalies_iso = df[df['anomaly'] == -1]

anomalies_iso.head()

,Temperature,Vibration,Pressure,EnergyConsumption,ProductionUnits,DefectCount,MaintenanceFlag,MachineID_101,MachineID_102,MachineID_103,...,MachineID_145,MachineID_146,MachineID_147,MachineID_148,MachineID_149,Plant_Plant_B,Plant_Plant_C,EnergyPerUnit,Z_score,anomaly
94,66.484017,2.748175,29.355462,329.311263,51,0,0,False,False,False,...,False,False,False,False,False,False,False,6.457084,3.947951,-1
103,72.691474,4.386384,33.713851,284.948057,56,4,0,False,False,False,...,False,False,False,False,False,False,True,5.088358,2.642628,-1
129,70.730706,4.775016,27.632971,282.909700,50,1,0,False,False,False,...,False,False,False,False,False,False,False,5.658194,3.186068,-1
146,66.367371,3.062829,17.558366,274.579004,53,1,0,False,False,False,...,False,False,False,False,False,True,False,5.180736,2.730727,-1
154,74.348250,4.806819,20.212055,292.081802,60,4,0,False,False,False,...,False,False,False,False,False,True,False,4.868030,2.432506,-1